
---
title: "Ruolo della fauna selvatica nella diffusione e  mantenimento  dell'antibiotico-resistenza \\ (PRC2016020)"
author: 'SINTESI'
header-includes: \usepackage[italian]{babel} \usepackage{setspace}\doublespacing \usepackage{float} 
                  \usepackage{booktabs} \usepackage{longtable} 
                  \usepackage{fontspec} \usepackage{caption}
                  \setmainfont{Times New Roman}
                  
              
output:
  pdf_document:
    latex_engine: xelatex
    #toc: yes
    number_sections: yes
    fig_caption: yes
    extra_dependencies: ["float"]
 
    
bibliography: amrRef.bib
link-citations: yes
linkcolor: blue
 

---

Responsabile scientifico: Dr. Tranquillo Vito (vito.tranquillo@izsler.it)

**Parole chiave:** antimicrobico-resistenza, fauna selvatica, resistoma ambientale. 

**Introduzione**

L'interesse per il ruolo della fauna selvatica nella diffusione e nel mantenimento dell'antibiotico-resistenza è aumentato nel corso degli ultimi 10 anni.  La principale preoccupazione nasce dal timore che l'eventuale dimostrazione di un ruolo della fauna selvatica come "serbatoio" e "mantenimento" di batteri portatori di geni di resistenza, contribuendo alla contaminazione ambientale di batteri resistenti o materiale genetico di resistenza, possa compromettere gli sforzi messi in atto, soprattutto in questi ultimi anni, in campo medico e veterinario per ridurre la diffusione del fenomeno dell'antibiotico-resistenza. La resistenza agli antibiotici è di per se un fenomeno naturale e come tale non sorprende il riscontro di ceppi antibiotico-resistenti in animali selvatici anche in aree remote del globo. I dati disponibili [@greig_scoping_2015] mostrano che numerose specie di animali selvatici sono portatori di  batteri antimicrobici resistenti  in una vasta gamma di habitat, il che solleva la questione del loro ruolo nelle dinamiche di diffusione e mantenimento all'interfaccia tra popolazioni umane, animali domestici ed ecosistemi naturali. La presenza nella fauna selvatica, normalmente non sottoposta a trattamenti antibiotici, di ceppi batterici resistenti e in generale di geni di resistenza, è verosimilmente attribuibile a fenomeni di contaminazione ambientale. 
Per definire il ruolo della fauna selvatica nel complesso meccanismo di diffusione e mantenimento dell'antibiotico resistenza è necessario acquisire informazioni relativamente a: quali specie di batteri sono le più frequentemente trovate resistenti ai farmaci antimicrobici nei vertebrati selvatici e la loro caratterizzazione fenotipica e soprattutto genotipica;  in che modo le specie selvatiche vengono colonizzate da batteri antibiotico-resistenti e quali scambi di tali batteri avvengono tra l'uomo, gli animali domestici e la fauna selvatica;  cosa caratterizza gli habitat più contaminati da batteri antibiotico-resistenti e infine quali tratti ecologici favoriscono la colonizzazione e la potenziale infezione da batteri antibiotico-resistenti nella fauna selvatica [@vittecoq_antimicrobial_2016]. Sulla base dei dati disponibili sulla diffusione in Italia e nel resto del mondo dell'antibiotico resistenza nella fauna selvativca è stato progettato un studio osservazionale con l'obiettivo  di raccogliere informazioni sulla presenza e diffusione dell'antibiotico-resistenza in ceppi batterici della famiglia delle Enterobacteriacee isolati da feci di un ampio spettro di specie di fauna selvatica, presente in varie province della Lombardia con differenti gradi di urbanizzazione, procedendo quindi alla loro caratterizzazione fenotipica  di resistenza e quella genotipica utilizzando metodiche di analisi metagenomica. 

**Materiali e Metodi**

Nel periodo compreso tra la fine del 2017 e primi mesi del 2019, si è proceduto ad un campionamento non probabilistico di convenienza utilizzando sia i campioni raccolti durante le attività di sorveglianza del piano regionale fauna selvatica della Lombardia (cinghiali, ruminanti selvatici, lagomorfi, volatili) , sia i campioni provenienti da attività di sorveglianza del piano Chronic Wasting Disease (cervi e caprioli) e del piano West Nile Disease (Cornacchie, Gazze). I campioni di feci sono stati quindi processati mediante comuni metodi di microbiologia classica per ottenere l'isolamento di ceppi di Enterobacteriacee, identificati mediante test biochimici sia in macro che micrometodo. I ceppi isolati sono stati testati con un panel di sette antibiotici (AMPICILLINA, TETRACICLINA, CEFTIOFUR, COLISTINA, KANAMICINA, GENTAMICINA, ENROFLOXACIN) per definirne il profilo fenotipico di resistenza. Ceppi di Escherichia coli risultati resistenti a CEFTIOFUR sono stati sottoposti ad analisi fenotipiche e genotipiche per la determinazione della presenza di enzimi ESBL. Dieci pool di ceppi di E.coli, raggurppati per specie di provenienza e per localizzazione geografica sono stati analizzati mediante tecniche di metagenomica per definirne i profili genotipici di resistenza. I dati fenotipici sono stati analizzati mediante metodi di statistica bayesiana per ottenere stime di prevalenza di animali carrier di ceppi resistenti e multi-resistenti e della prevalenza di ceppi resistenti e multi-resistenti e per studiare la relazione tra caratteristiche territoriali ( grado di antropomorfizzazione) e prevalenza di animali carrier di ceppi resistenti. La biodiversità dei differenti profili fenotipici è stata studiata mediante la definizione dei priofili di Renyi's. 


**Risultati e discussione**
L'attività di campionamento si è svolta tra Settembre 2017 e Dicembre 2018  in sette province della Lombardia : Bergamo, Pavia, Varese,Como, Lecco e Brescia da un totale di 223 comuni. Sono stati raccolti complessivamente 670 campioni di feci da 33 differenti specie di fauna selvatica.Dai 671 campioni di feci analizzati sono stati isolati  911 ceppi batterici identificati come appartenenti alla famiglia delle Enterobacteriacee. Escherichia coli (E.coli) rappresenta il 67.6% dei ceppi isolati, il restante 32% dei ceppi è distribuito su un totale di 14 generi differenti. Sono stati eseguiti 910 antibiogrammi. Complessivamente 392 ceppi (43%) sono risultati Suscettibili (S) al panel di antibiotici testati ; 423 (46%) i ceppi Resistenti (R)  fino ad un massimo di 2 antibiotici e infine 95 (10%) ceppi sono risultati Multiresistenti (MR), con resistenza a 3 o più antibiotici.Complessivamente da 670 campioni di feci di fauna selvatica da cui è stato  isolato almeno un ceppo di _Enterobacteriacee_ e su cui è stato eseguito l'antibiogramma, è stato isolato almeno un ceppo resistente ad uno o più  antibiotici del panel indagato in 421 campioni, pari ad una Prevalenza complessiva (Overall Prevalence) del 62% (95% HPD: 58-67%). La variabilità tra i gruppi-specie è particolarmente ampia: nei CORVIDI si osserva la prevalenza più elevata (84%), mentre nei  BOVIDI la più bassa (37%). A causa della bassa numerosità campionaria si osservano stime con incertezza molto ampia nei gruppi : LEPRE, ALTRI VOLATILI, UCCELLI ACQUATICI, CARNIVORI e RAPACI. Su 670 campioni di feci, 92 presentano almeno un ceppo MULTI-RESISTENTE (numero di resistenze >= a 3), pari ad una prevalenza del 14% (95% HPD:11%-16%). La variabilità tra gruppi specie risulta molto ampia: la prevalenza di animali selvatici portatori di ceppi multiresistenti varia da un minimo del 4% nel gruppo UCCELLI ACQUATICI ad un massimo dell'88% nella LEPRE. La bassa numerosità dei campioni di alcuni gruppi specie rende le stime molto incerte. L'associazione  tra prevalenza di casi resistenti e area adibita al pascolo è condizionalmente dipendente dal gruppo specie considerato; risultato ragionevole dal punto di vista biologico perchè riflette la differente frequentazione delle differenti specie in aree con diverso grado di urbanizzazione (le aree adibite al pascolo tendono a essere presenti in aree a minore grado di urbanizzazione). Si osserva comunque un aumentare della probabilità di osservare animali carrier di ceppi di Enterobacteriacee resistenti ad almeno un antibiotico, in tutti i gruppi specie con diversa entità, fatta eccezione per il gruppo CORVIDI, in cui all'aumentare dell'area adibita a pascolo si osserva una riduzione del rischio di animali carrier.I dati forniti da questo studio suggeriscono che, complessivamente,  il fenomeno della multi-resistenza, almeno per quello che riguarda la sua manifestazione fenotipica,  è  poco frequente pari a circa il 14% (95% HPD:11%-16%) nelle specie e nei territori indagati. Nel gruppo CORVIDI, maggiormente esposto a contaminazione da ambienti antropomorfizzati è pari al 21% (95% HPD:15%-28%).Le resistenze nei confronti di AMP e TET sono risultate le più frquenti: su 910 ceppi testati nei confronti di AMP 388 risultano resistenti (%), 342 ceppi risultano resistenti a TET (). Si osserva una frequenza di resistenza molto contenuta nei confronti degli altri antibiotici: solo l'8% di resistenze nei confronti di CFT, 5% nei confronti di COL, 5% nei confronti di ENR , 5% nei confronti di KAN e solo l'1.3% nei confronti di GEN. L'dentificazione genomica dei 47  ceppi ceftiofur-resistenti ha permesso di identificare Escherichia coli nell'85% dei casi  e  Escherichia fergusonii nel 15%. Nei ceppi di Escherichia coli è emersa una prevalenza dell’10% (4/40) per il gene TEM e del 2,50% (1/40) per SHV. Nei ceppi di Escherichia fergusonii, è stata riscontrata una prevalenza del 14,29% (1/7) per il gene SHV. Complessivamente si osservano 39 differenti profili fenotipici basati sulle resistenze osservate. I profili più frequenti  sono:  TET-AMP (141 ceppi), AMP (130 ceppi), TET (85 ceppi), CFT-TET-AMP (27 ceppi), COL-TET-AMP (14 ceppi), COL-TET (12 ceppi) e CFT-TET (12 ceppi), che rappresentano più dell'80% dei ceppi. . Nella popolazione di CERVIDI si osserva un profilo di dominanza in termini di diversità con una minore diversità di profili di co-resistenza con una forte dominanza di pochi profili. AL contrario i gruppi specie BOVIDI, SUIDI, CARNIVORI, LEPRE, UCCELLI ACQUATICI e ALRI VOLATILI, mostrano un profilo di uniformità (evenness), quindi caratterizzato da maggiore diversità senza la presenza di profili di co-resistenza relativamente dominanti.  Le popolazione di CORVIDI e RAPACI mostrano un  profilo di diversità sovrapponibile e intermedio  rispetto a quello di dominanza dei CERVIDI e di uniformità  degli altri gruppi-specie. I risultati di questo studio confermano la presenza di ceppi di _Enterobacteriacee_ resistenti in un ampio spettro di specie di fauna selvatica di un vasto territorio con differenti caratteristiche territoriali e pressione antropegenica. La prevalenza di ceppi multi-resistenti risulta contenuta e questo supporta quanto già descritto in letteratura [@hassell_clinically_2019-1] l'ipotesi che il comparto dei selvatici funga principalmente da contenitore accidentale del resistoma ambientale ma che l'assenza di continui stimoli selettivi ( somministrazione di antibiotici) non permette l'espansione clonale dei ceppi resistenti. Da questo punto di vista i selvatici assumono un ruolo di sentinella di ambienti contaminati dal resistoma ambientale. La riduzione della contaminazione ambientale dei residui di antibiotici e sotanze chimiche rappresenta il principale presidio per impedire che ceppi reistenti presenti nel microbioma delle specie selvatiche possano svilupparsi ed espandersi in modo critico innescando flussi di contaminazione verso gli animali domestici e popolazioni umane vanificando gli sforzi messi in atto in questi anni per ridurre il fenomeno dell'antibiotico-resistenza.

**Bibliografia**

