---
title: "Programmazione 2021-2022 dell'attività dell'ufficio di controllo di gestione e performance"
output: pdf_document
---

## Ciclo delle performances

L'attività dell'ufficio di controllo di gestione e performance è pienamente inserita nel ciclo delle performances e da questo governata


```{r include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(timevis)
library(reshape2)
library(hrbrthemes)
library("lubridate")
library("scales")
```


```{r eval=FALSE, include=FALSE}
timing <- read_excel( here ("Documenti Controllo di Gestione e Performances",   "timing.xlsx"), 
                     col_types = c( "text", "date", "date"))

timing <- timing %>% 
  mutate(event = factor(event, levels = c("Piano quadriennale dell'attività dell'IZSLER", 
                                          "Definizione obiettivi strategici/obiettivi operativi/indicatori/target : Piano delle performance", 
                                          "Scheda Budget (definzione/negoziazione con i dipartimenti)", 
                                          "Relazione sulla performance (anno 2021)")))  
 



  melt(timing,  measure.vars = c("start", "end")) %>% 
    mutate(event = fct_rev(event), 
           value = as.Date(value)) %>% 
  ggplot(aes(value, event,  color = event))+
  geom_line(size = 6, alpha = 0.8)+ 
  xlab(NULL) + 
  ylab(NULL) +
    theme_ipsum_rc()+
    theme(legend.position = "blank")+
    scale_x_date(labels = date_format("%m-%Y"), breaks = "1 month")+
    scale_color_manual(values=c(rep("#487DA8", 16)))

```


## Piano quadriennale

## Definizione obiettivi strategici, azioni, indicatori e target

## Scheda Budget

## Relazione delle performances

